### ISSUE TITLE
readthedocs not found

### ISSUE THREAD

**Issue by olebole** [yt-project/ewah_bool_utils#45]
The readthedocs URL https://ewah-bool-utils.readthedocs.io/ returns a 404.

**Comment by neutrinoceros** [comment]
To my knowledge the doc was ever hosted anywhere. We've had a badge pointing to that url (which I recently took down), but my understanding is that it was just generated from cookiecutter when the repo was started (correct me if I'm wrong, @matthewturk)

**Comment by olebole** [comment]
Thanks  for the explanation! 
Since this package is a dependency for yt, and I therefore need to package it for Debian, it would be great to have a short description of the package. At least I have no idea what "EWAH Bool Array compression" means.

**Comment by matthewturk** [comment]
@olebole ah!  Great point.  EWAH Bool Array compression is a repackaging and Python-exposed version of "Enhanced Word-Aligned Hybrid" (EWAH) compression.  It's a python wrapper to a compressed bitarray method, for storing large bitsets.

**Comment by matthewturk** [comment]
@olebole Thank you for packaging it -- I just saw debian bug #1038969!

**Comment by olebole** [comment]
That was so quick that I couldn't send it to you :-)

**Comment by neutrinoceros** [comment]
Anything else, or should we close this ? :)

**Comment by olebole** [comment]
I'd recommend to close it once the link is removed from the README.

**Comment by neutrinoceros** [comment]
Oh, I didn't realise it was still there 😅
